-- 车型详情：精简字段，仅保留用于列表/关联/状态控制的核心列 + raw

ALTER TABLE public.model_details
  DROP COLUMN IF EXISTS basic,
  DROP COLUMN IF EXISTS body,
  DROP COLUMN IF EXISTS drivingauxiliary,
  DROP COLUMN IF EXISTS engine,
  DROP COLUMN IF EXISTS actualtest,
  DROP COLUMN IF EXISTS gearbox,
  DROP COLUMN IF EXISTS chassisbrake,
  DROP COLUMN IF EXISTS aircondrefrigerator,
  DROP COLUMN IF EXISTS wheel,
  DROP COLUMN IF EXISTS entcom,
  DROP COLUMN IF EXISTS doormirror,
  DROP COLUMN IF EXISTS seat,
  DROP COLUMN IF EXISTS internalconfig,
  DROP COLUMN IF EXISTS light,
  DROP COLUMN IF EXISTS safe,
  DROP COLUMN IF EXISTS isnev,
  DROP COLUMN IF EXISTS incarcharge,
  DROP COLUMN IF EXISTS "4wdoffroad",
  DROP COLUMN IF EXISTS activesafety,
  DROP COLUMN IF EXISTS drivingcontrol,
  DROP COLUMN IF EXISTS wheelbrake,
  DROP COLUMN IF EXISTS appearanceantitheft,
  DROP COLUMN IF EXISTS color,
  DROP COLUMN IF EXISTS screensystem,
  DROP COLUMN IF EXISTS drivingfunction,
  DROP COLUMN IF EXISTS intelligentconfig,
  DROP COLUMN IF EXISTS externalrearmirror,
  DROP COLUMN IF EXISTS drivinghardware,
  DROP COLUMN IF EXISTS chassissteer,
  DROP COLUMN IF EXISTS passivesafety,
  DROP COLUMN IF EXISTS soundinteriorlight,
  DROP COLUMN IF EXISTS exteriorlight,
  DROP COLUMN IF EXISTS electricmotor,
  DROP COLUMN IF EXISTS sunroofglass;
