-- 修复所有表的权限设置
-- 确保 anon 和 authenticated 角色都能正常访问数据

-- 1. 为所有表授予 SELECT 权限给 anon 角色（用于公开访问）
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;

-- 2. 为所有表授予完整权限给 authenticated 角色（用于登录用户）
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;

-- 3. 确保序列的权限也正确设置
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- 4. 对于 future 创建的表设置默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO authenticated;

-- 5. 确保函数的执行权限
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO authenticated;
